[general]
# https://github.com/alacritty/alacritty-theme/
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
padding = { x = 10, y = 10 }

[scrolling]
history = 0

[font]
bold = { style = "Bold" }
bold_italic = { style = "Bold Italic" }
italic = { style = "Italic" }
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
size = 22

[cursor]
style = { blinking = "Always", shape = "Block" }
blink_interval = 300

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
