# https://github.com/alacritty/alacritty-theme/
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
blur = true
decorations = "buttonless"
option_as_alt = "Both"
padding.x = 10
padding.y = 10

[font]
bold_italic.style = "Bold Italic"
bold.style = "Bold"
italic.style = "Italic"
normal.family = "IosevkaTerm Nerd Font Mono"
normal.style = "Regular"
size = 19

[cursor]
blink_interval = 300
style.blinking = "Always"
style.shape = "Block"
unfocused_hollow = true

[scrolling]
history = 0
