// Generated by dv hooks install pi — do not edit by hand.
// Re-run `dv hooks install pi` to update.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFileSync } from "node:child_process";

function dv(...args: string[]): void {
  try {
    execFileSync("dv", args, { timeout: 5000, stdio: "ignore" });
  } catch {
    // Silently ignore errors (e.g. dv not in PATH, outside tmux)
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", async () => {
    dv("set-state", "idle", "--harness", "pi");
  });

  pi.on("before_agent_start", async () => {
    dv("set-state", "working", "--harness", "pi");
  });

  pi.on("agent_settled", async () => {
    dv("set-state", "done", "--harness", "pi");
  });

  pi.on("session_shutdown", async () => {
    dv("clear-state");
  });
}
