// Generated by rd hooks install pi — do not edit by hand.
// Re-run `rd hooks install pi` to update.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFileSync } from "node:child_process";

function rd(...args: string[]): void {
  try {
    execFileSync("rd", args, { timeout: 5000, stdio: "ignore" });
  } catch {
    // Silently ignore errors (e.g. rd not in PATH, outside tmux)
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", async () => {
    rd("set-state", "idle", "--harness", "pi");
  });

  pi.on("before_agent_start", async () => {
    rd("set-state", "working", "--harness", "pi");
  });

  pi.on("agent_settled", async () => {
    rd("set-state", "done", "--harness", "pi");
  });

  pi.on("session_shutdown", async () => {
    rd("clear-state");
  });
}
