// Generated by rd install pi — do not edit by hand.
// Re-run `rd install pi` to update.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFileSync } from "node:child_process";

function rd(...args: string[]): void {
  try {
    execFileSync("rd", args, { timeout: 5000, stdio: "ignore" });
  } catch {
    // Silently ignore errors (e.g. rd not in PATH, outside tmux)
  }
}

export default function (pi: ExtensionAPI) {
  let runId: string | undefined;

  pi.on("session_start", async () => {
    const sessionId = crypto.randomUUID();
    rd("agent", "event", "SESSION_STARTED", "--id", sessionId, "--harness", "pi");
  });

  pi.on("before_agent_start", async () => {
    runId = crypto.randomUUID();
    rd("agent", "event", "RUN_STARTED", "--id", runId, "--harness", "pi");
  });

  pi.on("agent_settled", async () => {
    if (runId) {
      rd("agent", "event", "RUN_FINISHED", "--id", runId, "--harness", "pi");
    }
  });

  pi.on("tool_call", async (event) => {
    rd("agent", "event", "TOOL_CALL_START", "--id", event.toolCallId, "--harness", "pi");
  });

  pi.on("tool_result", async (event) => {
    rd("agent", "event", "TOOL_CALL_RESULT", "--id", event.toolCallId, "--harness", "pi");
  });

  pi.on("session_shutdown", async () => {
    rd("agent", "clear");
  });
}
