"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$git_branch$character"""

[git_branch]
format = """[$symbol$branch(:$remote_branch)]($style) """
symbol = '🌱'
