#!/bin/zsh

export PATH=$PATH:$HOME/.local/bin
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share

# Initialize Brew
export HOMEBREW_BUNDLE_FILE=$XDG_CONFIG_HOME/brewfile/Brewfile
if [ -f /usr/local/bin/brew ]; then
    # Intel MacOS
    eval "$(/usr/local/bin/brew shellenv)"
elif [ -f /opt/homebrew/bin/brew ]; then
    # ARM MacOS
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Start tmux
if [ -x "$(command -v tmux)" ]; then
    export TERMINFO_DIRS=$TERMINFO_DIRS:$HOME/.local/share/terminfo # See https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/
else
    echo "Error: tmux is not installed"
fi

eval "$(starship init zsh)"

# Setup autocompletion system
autoload -Uz compinit
if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
    compinit
else
    compinit -C
fi

# Default editor
if [ -x "$(command -v nvim)" ]; then
    export VISUAL=nvim
else
    echo "Error: nvim is not installed"
fi

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob=\!.git/'
export FZF_DEFAULT_OPTS="--border=rounded \
  --color=bg+:#313244,bg:-1,gutter:-1,spinner:#f5e0dc,hl:#f38ba8 \
  --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
  --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8" # catppuccin mocha
# export FZF_DEFAULT_OPTS="
#   --color=fg:#e5e9f0,hl:#81a1c1
#   --color=fg+:#e5e9f0,hl+:#81a1c1
#   --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
#   --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b" # nord
export FZF_CTRL_T_COMMAND='fd --hidden --exclude ".git"'
export FZF_CTRL_T_OPTS="--border=rounded --color='border:12'"

# FNM
if [ -x "$(command -v fnm)" ]; then
    eval "$(fnm env --log-level quiet --use-on-cd)"
else
    echo "Error: fnm is not installed"
fi

# Other environment variables
if [ -f ~/.env.zsh ]; then
    source ~/.env.zsh
fi

# Secrets
if [ -f ~/.secrets.zsh ]; then
    source ~/.secrets.zsh
fi
