theme = "dracula_transparent"

[editor]
auto-pairs = false
color-modes = true
cursorline = true
line-number = "relative"
mouse = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
newline = "all"
