[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 2, unit = "  " }