# Taps
tap "homebrew/cask-fonts"
tap "oven-sh/bun"

# Terminal
cask "alacritty"
brew "zsh"
brew "zsh-autosuggestions"
brew "tmux"
brew "tpm"
cask "font-iosevka"
brew "starship"

# CLIs
brew "git"
brew "gh"
brew "neovim"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "stow"
brew "tree"
brew "eza"

# Programming tools
brew "rust"
brew "rust-analyzer"
brew "rustfmt"
brew "fnm"
brew "marksman"
cask "docker"
brew "bun"

# Other
cask "drawio"
cask "syncthing"
cask "rectangle"
cask "arc"
