[[language]]
name = "javascript"
auto-format = false

[[language]]
name = "typescript"
auto-format = false

[[language]]
name = "jsx"
auto-format = false

[[language]]
name = "tsx"
auto-format = false

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 2, unit = "  " }