# Taps
tap "homebrew/cask-fonts"
tap "oven-sh/bun"
tap "hashicorp/tap"

# Terminal
cask "alacritty"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "tmux"
brew "tpm"
brew "starship"
cask "font-iosevka-term-nerd-font"

# CLIs
brew "git"
brew "gh"
brew "neovim"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "stow"
brew "tree"
brew "eza"
brew "bat"
brew "tlrc"

# Programming tools
brew "rust"
brew "rust-analyzer"
brew "rustfmt"
brew "fnm"
brew "marksman"
cask "docker"
brew "bun"
brew "ansible"
brew "hashicorp/tap/terraform"
brew "helm"
brew "helmfile"

# Other
cask "drawio"
cask "syncthing"
cask "rectangle"
cask "arc"
brew "sshpass" # for ansible
