theme = "catppuccin_mocha_transparent"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
newline = "all"
