[[language]]
name = "javascript"
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "jsx"
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwind-lsp" ]
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "html"
formatter = { command = 'bunx', args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'bunx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = 'bunx', args = ["prettier", "--parser", "markdown"] }

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }

[language-server.tailwind-lsp]
command = "tailwindcss-language-server"
args = ["--stdio"]
