import = ["~/.config/alacritty/themes/nord.toml"]

[cursor]
blink_interval = 300
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 18

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[scrolling]
history = 0

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 8
y = 8
